! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


SUBROUTINE C_TEST_STANDARD(STEPS, SOLUTION, MAX_WINDOW_PRESENT, MAX_WINDOW) BIND(C)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: STEPS

  REAL, INTENT(INOUT) :: SOLUTION

  LOGICAL, INTENT(IN) :: MAX_WINDOW_PRESENT
  REAL, INTENT(IN) :: MAX_WINDOW

  INTERFACE
    SUBROUTINE TEST_STANDARD(STEPS, SOLUTION, MAX_WINDOW)
    IMPLICIT NONE
      INTEGER, INTENT(IN) :: STEPS
      REAL, INTENT(INOUT) :: SOLUTION
      REAL, INTENT(IN), OPTIONAL :: MAX_WINDOW
    
      INTERFACE
        FUNCTION QUADRATIC(X) RESULT(Y)
          REAL, INTENT(IN) :: X
          REAL :: Y
        END FUNCTION QUADRATIC
      END INTERFACE
    END SUBROUTINE TEST_STANDARD
  END INTERFACE

  IF (MAX_WINDOW_PRESENT) THEN
    CALL TEST_STANDARD(STEPS=STEPS, SOLUTION=SOLUTION, MAX_WINDOW=MAX_WINDOW)
  ELSE
    CALL TEST_STANDARD(STEPS=STEPS, SOLUTION=SOLUTION)
  END IF
END SUBROUTINE C_TEST_STANDARD

