!     Module generated by fmodpy for fortran file named 'CODE'     
!=====================================================================
MODULE CODE_WRAPPER
  ! Any necessary "USE" statements
  USE ISO_FORTRAN_ENV
  ! Make sure it is clear that no implicit types are used in this wrapper
  IMPLICIT NONE
  ! Any interfaces defined for "PROCEDURE" declarations
  
    
  INTERFACE
     ! Fortran interface for passing assumed shapes to non-moduled functions.
     SUBROUTINE RESERVE( S, OUTPUT )
       USE ISO_FORTRAN_ENV
       INTEGER(KIND=INT64), INTENT(IN) :: S
       REAL(KIND=REAL64), DIMENSION(:), INTENT(OUT), ALLOCATABLE :: OUTPUT
     END SUBROUTINE RESERVE
  END INTERFACE
    
    

CONTAINS
  !     Fortran wrapper for RESERVE, callable from C     
  !========================================================

   SUBROUTINE c_RESERVE( S, OUTPUT_0, OUTPUT ) BIND(c)
    ! This subroutine's only purpose is to call the source fortran
    !  code while also being accessible from C.
    INTEGER(KIND=INT64), INTENT(IN) :: S
    INTEGER, INTENT(OUT) :: OUTPUT_0
    REAL(KIND=REAL64), DIMENSION(:), POINTER, INTENT(OUT) :: OUTPUT
    ! Allocate memory at the output location.
    REAL(KIND=REAL64), DIMENSION(:), ALLOCATABLE :: OUTPUT_HOLDER
    ! Preparation code before function call (copying character arrays)
    PRINT '(" entered c_RESERVE, calling reserve.. ")'
    ! Calling source fortran function
    CALL RESERVE(S, OUTPUT_HOLDER)
    PRINT '(" done with RESERVE.. ")'
    ! Copying out any necessary values for return (character arrays)
    OUTPUT_0 = SIZE(OUTPUT_HOLDER)
    OUTPUT = OUTPUT_HOLDER
    PRINT '(" assigned OUTPUT_0.. ",I10)', OUTPUT_0
    
  END SUBROUTINE c_RESERVE

END MODULE CODE_WRAPPER
