
PROGRAM SIZE_TEST
  USE ISO_FORTRAN_ENV
  IMPLICIT NONE
  
    INTEGER(KIND=INT64) :: SIZE
    REAL(KIND=REAL64) :: OUTPUT
  
    PRINT *, 'SIZE', SIZEOF(SIZE)
    PRINT *, 'OUTPUT', SIZEOF(OUTPUT)
END PROGRAM SIZE_TEST

