! This routine says hello.
SUBROUTINE SAY_HELLO(A,B,C,D)
  USE ISO_FORTRAN_ENV, ONLY: INT64, REAL64
  INTEGER(KIND=INT64), INTENT(IN) :: A
  REAL(KIND=REAL64), INTENT(IN) :: B
  INTEGER, INTENT(OUT) :: C
  REAL, INTENT(OUT) :: D
  print *, 'Hello!'
  C = A
  D = B
END SUBROUTINE SAY_HELLO
