!     Module generated by fmodpy for fortran file named 'SINGLE_MODULE'     
!=====================================================================
MODULE SINGLE_MODULE_WRAPPER
  ! Any necessary "USE" statements
  USE ISO_FORTRAN_ENV
  USE SIMPLE_TEST
  ! Make sure it is clear that no implicit types are used in this wrapper
  IMPLICIT NONE
  ! Any interfaces defined for "PROCEDURE" declarations
  
CONTAINS
  !     Fortran wrapper for ADD, callable from C     
  !========================================================

   SUBROUTINE c_ADD( ADD_A, ADD_B, ADD_C ) BIND(c)
    ! This subroutine's only purpose is to call the source fortran
    !  code while also being accessible from C.
    REAL(KIND=REAL64), INTENT(IN) :: ADD_A
    REAL(KIND=REAL64), INTENT(IN) :: ADD_B
    REAL(KIND=REAL64), INTENT(OUT) :: ADD_C
    ! Preparation code before function call (copying character arrays)
    
    ! Calling source fortran function
    CALL ADD(ADD_A, ADD_B, ADD_C)
    ! Copying out any necessary values for return (character arrays)
    
  END SUBROUTINE c_ADD


  !     Fortran wrapper for TAUTOLOGY, callable from C     
  !========================================================

   SUBROUTINE c_TAUTOLOGY( YES_OUTPUT ) BIND(c)
    ! This subroutine's only purpose is to call the source fortran
    !  code while also being accessible from C.
    LOGICAL :: YES_OUTPUT
    ! Preparation code before function call (copying character arrays)
    
    ! Calling source fortran function
    YES_OUTPUT = TAUTOLOGY()
    ! Copying out any necessary values for return (character arrays)
    
  END SUBROUTINE c_TAUTOLOGY


  !     Fortran wrapper for FALSEHOOD, callable from C     
  !========================================================

   SUBROUTINE c_FALSEHOOD( FALSEHOOD_OUTPUT ) BIND(c)
    ! This subroutine's only purpose is to call the source fortran
    !  code while also being accessible from C.
    LOGICAL :: FALSEHOOD_OUTPUT
    ! Preparation code before function call (copying character arrays)
    
    ! Calling source fortran function
    FALSEHOOD_OUTPUT = FALSEHOOD()
    ! Copying out any necessary values for return (character arrays)
    
  END SUBROUTINE c_FALSEHOOD


  !     Fortran wrapper for SUBTRACT, callable from C     
  !========================================================

   SUBROUTINE c_SUBTRACT( SUB_A, SUB_B, SUB_C_OUTPUT ) BIND(c)
    ! This subroutine's only purpose is to call the source fortran
    !  code while also being accessible from C.
    REAL, INTENT(IN) :: SUB_A
    REAL, INTENT(IN) :: SUB_B
    REAL :: SUB_C_OUTPUT
    ! Preparation code before function call (copying character arrays)
    
    ! Calling source fortran function
    SUB_C_OUTPUT = SUBTRACT(SUB_A, SUB_B)
    ! Copying out any necessary values for return (character arrays)
    
  END SUBROUTINE c_SUBTRACT


  !     Fortran wrapper for MULTIPLY, callable from C     
  !========================================================

   SUBROUTINE c_MULTIPLY( MULT_A, MULT_B, MULTIPLY_OUTPUT ) BIND(c)
    ! This subroutine's only purpose is to call the source fortran
    !  code while also being accessible from C.
    REAL, INTENT(IN) :: MULT_A
    INTEGER(KIND=INT64), INTENT(IN) :: MULT_B
    REAL :: MULTIPLY_OUTPUT
    ! Preparation code before function call (copying character arrays)
    
    ! Calling source fortran function
    MULTIPLY_OUTPUT = MULTIPLY(MULT_A, MULT_B)
    ! Copying out any necessary values for return (character arrays)
    
  END SUBROUTINE c_MULTIPLY

END MODULE SINGLE_MODULE_WRAPPER
